# Generated by Django 4.0.5 on 2022-11-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_employee_location_branch_alter_user_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_contact',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
