# Generated by Django 4.1.2 on 2022-10-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0005_softwaretype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('purchased_on', models.DateField(verbose_name='')),
                ('expiry', models.DateField(verbose_name='')),
                ('softwaretype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.softwaretype')),
            ],
        ),
    ]
