# Generated by Django 4.0.5 on 2022-11-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_hardware_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('hardware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.software')),
            ],
        ),
    ]
