# Generated by Django 4.0.5 on 2022-11-03 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_smh'),
    ]

    operations = [
        migrations.AddField(
            model_name='smh',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.software'),
        ),
        migrations.AlterField(
            model_name='smh',
            name='hardware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.hardware'),
        ),
    ]
