# Generated by Django 4.0.5 on 2022-11-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_smh_software_alter_smh_hardware'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMH',
        ),
    ]
