# Generated by Django 4.0.5 on 2022-11-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_smh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='brand',
        ),
    ]
