# Generated by Django 4.0.5 on 2022-11-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_hardware_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='emp_loc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
