# Generated by Django 4.0.5 on 2022-11-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_rename_branch_location_branch_branch_name_and_more'),
        ('product', '0010_hardware_emp_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='master.asset_location'),
        ),
    ]
