# Generated by Django 4.0.5 on 2022-11-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_softwaretype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
