# Generated by Django 4.0.5 on 2022-11-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_company_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_number',
            new_name='vendor_code',
        ),
    ]
