# Generated by Django 4.0.5 on 2022-11-09 06:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_rename_vendor_number_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
