# Generated by Django 4.0.5 on 2022-11-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_vendor_vendor_contact_alter_vendor_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_code',
        ),
    ]
