# Generated by Django 4.0.5 on 2022-11-09 11:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_remove_vendor_vendor_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch_location',
            new_name='branch_name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='address',
            new_name='vendor_address',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='email',
            new_name='vendor_email',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='website',
            new_name='vendor_website',
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_contact_person',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_contact_person_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
    ]
